### PR TITLE
Implemented widget-vue

### PR DESCRIPTION
**Pull request by zAlweNy26**
# Description

Implemented the widget present in the widget-vue repo. Removed unused code already implemented in the widget.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Current bugs:
- the admin css styles override the widget internal styles, creating color mistakes for the elements inside of it.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by zAlweNy26** [comment]
@pieroit I would like you to test it before merging.

**Comment by pieroit** [comment]
Ok @zAlweNy26 thanks, will revoew ASAP

**Comment by pieroit** [comment]
Bring back the dockerfiles please!

**Comment by zAlweNy26** [comment]
Ok, I thought they weren't needed anymore

**Pull request closed without merging**
