### PR TITLE
Update packages and fix CSS

### PR DESCRIPTION
**Pull request by zAlweNy26**
# Description

Just some tweaks and updates,

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by zAlweNy26** [comment]
@kodaline feel free to test it too :)

**Comment by EugenioPetulla** [comment]
The PR is generally good! :D

The only think I'm noticing is that the"upload" and "create" plugin buttons in the plugins page are too big for the scope, we should make them xs in order to better fit the rest of UX.

**Comment by zAlweNy26** [comment]
The "upload" and "create" plugin buttons are medium size, they seem fine to me, but making them smaller could be a little too much.

For the wipe button on the memory page, it is @kodaline's fault 🤣
I'll move it to bottom, I agree with you.

**Comment by kodaline** [comment]
> The "upload" and "create" plugin buttons are medium size, they seem fine to me, but making them smaller could be a little too much.
> 
> For the wipe button on the memory page, it is @kodaline's fault 🤣

I am sorry, when I did the heavy endpoints, I was wiping the memory without using the search bar, so without seeing the 2D memory graph. What was happening was that the `wipe buttons` where going down as if there was the graph but there wasn't, so I interpreted it as "bug".

Sorry again, @zAlweNy26 I can fix it if you want

**Comment by zAlweNy26** [comment]
No problem, I fixed it :)

**Pull request merged**
